Controllers films users SPRINT-9
Jon7even/java-filmorate pull request #2
Opened 2023-04-18 12:12 UTC by Jon7even

Два дня решал проблему с веткой. Почти стер и заново запушил, поэтому такая неразбериха в коммитах(

2023-04-18 15:04 UTC, andrew-larkin requested changes
Привет! Хорошая реализация функционала, чистый код. В тестах немного исправить и будем готовы двигаться дальше.

2023-04-18 15:04 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    private FilmController filmController;
в целом мы можем так сделать, но для тестов контроллера лучше использовать mockMvc

2023-04-23 10:12 UTC, Jon7even commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    private FilmController filmController;
Сначала не понял. Потом опять не понял:). Потом все читал подряд и понял, что нужно больше знаний про сервисы, базы, mock. Закопался, кое-как остановился. В итоге только сегодня смог реализовать. Напрягает, что тесты на валидацию находятся так же в  FilmControllerTest.class не знаю насколько это правильно. Спросить не у кого, потому что одногруппники тесты на MockMvc не делали.

2023-04-23 10:16 UTC, Jon7even commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    private FilmController filmController;
[src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java](https://github.com/Jon7even/java-filmorate/pull/2/files/65e04a8363e234e7a4b4991a3216346564c0627b#diff-913b24c9ddc6fb5dac3c3673b3e72bf2941a2f541530cc7c33bd9c1f1b88c74f)

2023-04-23 10:23 UTC, Jon7even commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void resetFilmService() {
Если я правильно понял, когда мы будем работать с БД, то у них уже есть такой метод. В данном случае я его реализовал для тестов, но ощущение, что так не должно быть.

2023-04-23 10:35 UTC, Jon7even commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        films.clear();
Если я правильно понял, когда мы будем работать с БД, то у них уже есть такой метод. В данном случае я его реализовал для тестов, но ощущение, что так не должно быть.

2023-04-24 11:05 UTC, merged